services:
  web:
    build: .
    container_name: github_webhook_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/webhookdb
    volumes:
      - .:/app

  db:
    image: postgres:14
    container_name: github_webhook_db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webhookdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
