"""remove total_count from reactions

Revision ID: 5a0a148d4535
Revises: d223dcf005e8
Create Date: 2025-04-17 09:36:11.410909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0a148d4535'
down_revision: Union[str, None] = 'd223dcf005e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactions', 'total_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('total_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
