"""add performed_via_github_app field to issue

Revision ID: d223dcf005e8
Revises: fc0568858e2c
Create Date: 2025-04-16 16:57:53.910298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd223dcf005e8'
down_revision: Union[str, None] = 'fc0568858e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('performed_via_github_app', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'performed_via_github_app')
    # ### end Alembic commands ###
